### ISSUE TITLE
Syllabus presentation

### ISSUE THREAD

**Issue by henryyang42** [henryyang42/NTHU_Course#1]
Now, we have the syllabus of all courses.
Currently, we use popup to represent the info, but it occupies the whole screen, which is not a good experience for uses.
Should we need to use popup, we can customize the css animation to make it prettier.

By the way, can someone make the syllabus table prettier XD

**Comment by leVirve** [comment]
What about this ?
I made some change in css3 and a little javascript of the result page to remove not necessary and rearrange the table. Is it okay to use css3 feature ?

![screenshot from 2015-05-09 03 09 01](https://cloud.githubusercontent.com/assets/7029882/7547714/1b6448a4-f625-11e4-974e-c9afd43d12dc.png)

**Comment by henryyang42** [comment]
Brilliant!

**Comment by henryyang42** [comment]
Brilliant!

**Comment by hydai** [comment]
Sure. Actually, I prefer using HTML5 and CSS3.
Awesome!
