### ISSUE TITLE
目前暫存功能好像失效了？

### ISSUE THREAD

**Issue by hydai** [henryyang42/NTHU_Course#100]
當我選擇一門課以後，只要對他進行重新整理頁面，他就會把我的選課記錄清空了。

**Comment by hydai** [comment]
我的環境是 Firefox 46.0.1

**Comment by henryyang42** [comment]
local storage 沒有對應到正確的學期，修改為10510可以正常運行。
https://github.com/henryyang42/NTHU_Course/blob/master/table/static/js/selectCourse.js#L2

**Comment by hydai** [comment]
Actually, it should not be 10501.
The correct value is 10510.

**Comment by henryyang42** [comment]
Roger that!
