### ISSUE TITLE
tesseract -> scikit-learn

### ISSUE THREAD

**Issue by afq984** [henryyang42/NTHU_Course#112]
Scikit-learn is easier to install than tessearct.

[My experiment](https://github.com/afg984/nthu-ccc/blob/master/nthuccc/decaptcha.py) with 1000 tests shows 99.8% pass rate
Probably integrate with it or port it

**Comment by henryyang42** [comment]
Scikit-learn <3

**Comment by hydai** [comment]
Cool!

**Comment by leVirve** [comment]
👍
