### ISSUE TITLE
[small Issues] 404 Error Page 

### ISSUE THREAD

**Issue by lockys** [henryyang42/NTHU_Course#47]
Just a small issue which needs small fixes.
http://nthu-course.cf/AcademicInformationSystemsSucks
Of course, the page doesn't exist.
But the hyperlink of '重新開始' directs me to the http://nthu-course.cf/index.html, not http://nthu-course.cf
The link, http://nthu-course.cf/index.html, shows the nginx's welcome page.

Nice work, I think this project will be very helpful for NTHU students :+1: :+1:

**Comment by hydai** [comment]
Thanks. It fixed in `dev` branch e705ba03394d8f444458d7eecba512af016b8431.
