### ISSUE TITLE
必選修 vs 通識向度 wrong search results

### ISSUE THREAD

**Issue by afq984** [henryyang42/NTHU_Course#57]
![image](https://cloud.githubusercontent.com/assets/4318379/8053503/ea0fbf38-0ec3-11e5-99f2-3a411f833986.png)

reproduction:
1. 選開課代號
2. 選 "必選修"
3. 搜尋
4. 選 GEC
5. 選 "向度"
6. 搜尋

**Comment by henryyang42** [comment]
Thanks for reporting! I will fix this very shortly.

**Comment by afq984** [comment]
merged
