### ISSUE TITLE
jQuery UI tooltip bug

### ISSUE THREAD

**Issue by afq984** [henryyang42/NTHU_Course#63]
1. click "大綱"
2. close it
3. tooltip still there

![image](https://cloud.githubusercontent.com/assets/4318379/8100214/3c310e2a-103b-11e5-9126-c96637c101df.png)

**Comment by henryyang42** [comment]
It's a known issue. @hydai  please fix this.

**Comment by henryyang42** [comment]
https://www.google.com.tw/webhp?sourceid=chrome-instant&ion=1&espv=2&es_th=1&ie=UTF-8#q=jquery+ui+tooltip+won%27t+disappear
