### ISSUE TITLE
lookup courses by Course.no

### ISSUE THREAD

**Issue by afq984** [henryyang42/NTHU_Course#71]
after crawling, previously selected courses (syllabus) become unavailable

![image](https://cloud.githubusercontent.com/assets/4318379/8125162/c5da6d26-1115-11e5-87a0-bc1247a3d235.png)

**Comment by hydai** [comment]
Which class is unavailable?
In the website or in the `dev` branch?

**Comment by henryyang42** [comment]
Yes, it's a know issue. We will change the index in future release.

**Comment by afq984** [comment]
@hydai after crawling, the primary key (`pk` or `id`) changes thus become unavailable

**Comment by hydai** [comment]
Yes, we found this issue in the beginning.
So the deployed machine inherit from old data. It will totally change after we use `crawl_course clear`
