### ISSUE TITLE
Search result transition is strange

### ISSUE THREAD

**Issue by henryyang42** [henryyang42/NTHU_Course#8]
![2015-05-26 4 49 19](https://cloud.githubusercontent.com/assets/6128538/7808649/5f6441da-03c7-11e5-985c-05877c19f750.png)

When I resubmit search, it's likely that the original table will still there until the new one replaces the old one. Can you refine the transition to achieve better user experience?

**Comment by leVirve** [comment]
Does it always happen?
There's only one table instance. What I've done is add some animation on it. 
With some tests, I face the same problem on my Chrome v.43, but it seems to work fine on Firefox.
After all, I'll make some search for the problem.

**Comment by leVirve** [comment]
Fixed it !
