### ISSUE TITLE
Course.teacher is fucked up

### ISSUE THREAD

**Issue by afq984** [henryyang42/NTHU_Course#86]
Branches affected: `master`, `dev`

The field Course.teacher expects at most 40 characters, and only store Chinese names.
The teacher field in syllabs used to show only Chinese, so it was not a problem then.
However, now, english names are included.
![image](https://cloud.githubusercontent.com/assets/4318379/11545579/f2bc037c-9982-11e5-87d6-f542f7cad497.png)

`DataError: value too long for type character varying(40)` pops out.

**Comment by afq984** [comment]
I'll be working on a fix targeting branch `dev`.

**Comment by afq984** [comment]
`Course.room` in `dev` is also affected. (not sure about `master`)
![image](https://cloud.githubusercontent.com/assets/4318379/11546632/6b1d0b12-9989-11e5-97c0-81b61655e4ea.png)
(from `10410CS  135502`)

The current `max_length` for `Course.room` is `20` and as I can recall there used not to be English prefixes in the syllabus.

I'd simply increase `max_length` for `Course.room` for this case, though.

**Comment by afq984** [comment]
Merged

**Comment by henryyang42** [comment]
I like the issue title. +1

**Comment by afq984** [comment]
Haha >.^

**Comment by afq984** [comment]
There will be courses with more than 7 teachers in 10420, thus breaking Course.teacher again.

I propose to increase the max_length to adapt it.

**Comment by afq984** [comment]
No longer a issue now
