### ISSUE TITLE
Encoding is borken in some page

### ISSUE THREAD

**Issue by hydai** [henryyang42/NTHU_Course#9]
Check 10320EE 221000.
![2015-05-27 12 16 41](https://cloud.githubusercontent.com/assets/2776756/7817187/b4dc50ce-0405-11e5-893b-9d7ebd627cb5.png)

**Comment by henryyang42** [comment]
![2015-05-27 7 53 06](https://cloud.githubusercontent.com/assets/6128538/7825935/760f726e-0445-11e5-9338-8ee070aa9683.png)
Accident do happen.

**Comment by hydai** [comment]
We still have trouble in this case.
